version: '3.8'

services:
  db:
    image: postgres:16-alpine  
    container_name: fepa-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=FepaDb
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data_new:/var/lib/postgresql/data  

  api:
    build:
      context: ../src/backend/Fepa.CoreService
      dockerfile: Fepa.API/Dockerfile
    container_name: fepa-api
    ports:
      - "5002:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=FepaDb;Username=postgres;Password=123456
    depends_on:
      - db

  web-admin:
    build:
      context: ../src/clients/web-admin
      dockerfile: Dockerfile
    container_name: fepa-web-admin
    ports:
      - "3000:80"
    depends_on:
      - api
volumes:
  postgres_data_new:  